name: Maven integration test

on:
  pull_request:    
    branches:
      - main
  push:
    branches:
    - 'ci/**'

jobs:
  integration-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Integration test with Maven
      run: ./mvnw -B clean integration-test --file pom.xml
