name: Maven verify and Docker build and publish

on:
  push:
    branches:
    - main

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Verify with Maven
      run: ./mvnw -B clean verify --file pom.xml

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
  
  docker-build-publish:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v4
      with:
        name: java-app
    - name: Docker login
      run: docker login ghcr.io -u imre-gabor -p ${{ github.token }}
    - name: Docker build
      run: docker build . -t ghcr.io/imre-gabor/cubix/1/optional/app:springboot
    - name: Docker publish
      run: docker push ghcr.io/imre-gabor/cubix/1/optional/app:springboot